<a href="https://colab.research.google.com/github/NastuaBudko/machine_learning/blob/main/%D0%91%D1%83%D0%B4%D0%BA%D0%BE_%D0%BF%D1%80_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Будко А.С. ФІТ 4-8
Варіант 2(4)

Завдання 1: Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та
виведіть його значення.


In [2]:
import numpy as np

vector = np.arange(1, 21)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


Завдання 2: Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його випадковими
натуральними числами та виведіть його значення.


In [3]:
matrix = np.random.randint(1, 101, size=(3, 3))
print(matrix)

[[25 90 12]
 [24 81 25]
 [24 22 39]]


Завдання 3: Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від -1 до 1 та виведіть його значення.


In [4]:
matrix = np.random.uniform(-1, 1, size=(5, 5))
print(matrix)

[[-0.93740147 -0.99039477 -0.14013727 -0.25422028  0.44878802]
 [ 0.42869095 -0.73043109 -0.75010677  0.24147894 -0.72914853]
 [ 0.85268325 -0.50682448 -0.9244906   0.73947389  0.45140125]
 [-0.46948737 -0.48204161  0.21092191 -0.32649594  0.66834576]
 [ 0.23314144  0.35230981 -0.61808891  0.4698449  -0.61935686]]


Завдання 4: Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть середнє значення елементів.

In [5]:
matrix = np.random.uniform(0, 1, size=(5, 5))

average_value = np.mean(matrix)

print("Matrix:")
print(matrix)
print("Average:")
print(average_value)

Matrix:
[[0.19785162 0.73738862 0.57230065 0.94762216 0.65922663]
 [0.70356761 0.1116128  0.94831517 0.09828395 0.69451056]
 [0.82474818 0.32114804 0.98558678 0.52503458 0.59220275]
 [0.13218592 0.65895303 0.11400811 0.15684631 0.55684334]
 [0.88926746 0.42213535 0.66732914 0.41622001 0.22827226]]
Average:
0.5264584414076934


Завдання 5: Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
числами в діапазоні від -10 до 10 та виконайте на них поелементні операції додавання,
віднімання та множення.


In [6]:
array1 = np.random.randint(-10, 11, size=5)
array2 = np.random.randint(-10, 11, size=5)

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2

print("Array1:")
print(array1)
print("Array1:")
print(array2)
print("Addition:")
print(addition)
print("Subtraction:")
print(subtraction)
print("Multiplication:")
print(multiplication)

Array1:
[ 1 -6 -1  9  8]
Array1:
[ 5  6 10  9 -6]
Addition:
[ 6  0  9 18  2]
Subtraction:
[ -4 -12 -11   0  14]
Multiplication:
[  5 -36 -10  81 -48]


Завдання 6: Створіть дві матриці 2x2, заповніть їх довільними дійсними числами від 3 до 10 та
знайдіть їх добуток.

In [7]:

matrix1 = np.random.uniform(3, 10, size=(2, 2))
matrix2 = np.random.uniform(3, 10, size=(2, 2))
product = np.dot(matrix1, matrix2)

print("Matrix1:")
print(matrix1)
print("Matrix2:")
print(matrix2)
print("Product:")
print(product)

Matrix1:
[[5.50519474 9.04350062]
 [4.71585097 3.50460787]]
Matrix2:
[[8.40210893 6.49239426]
 [6.9052684  9.12120501]]
Product:
[[108.70304494 118.22951792]
 [ 63.82335153  62.58341065]]


Завдання 7: Створіть дві матриці розміром 2x3 та 3x2, заповніть їх випадковими цілими числами
в діапазоні від 1 до 5 та перемножте їх між собою.


In [8]:
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 2))
product = np.dot(matrix1, matrix2)

print("Matrix1:")
print(matrix1)
print("Matrix1:")
print(matrix2)
print("Product:")
print(product)

Matrix1:
[[5 3 3]
 [2 4 4]]
Matrix1:
[[5 5]
 [3 2]
 [1 5]]
Product:
[[37 46]
 [26 38]]


Завдання 8: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від 1 до 12 та знайдіть її обернену матрицю.


In [9]:
matrix = np.random.randint(1, 13, size=(3, 3))

print(matrix)

det = np.linalg.det(matrix)
if det == 0:
    print("Inverse matrix does not exist.")
else:
    inverse_matrix = np.linalg.inv(matrix)

    print("Inverse matrix:")
    print(inverse_matrix)

[[ 3  9  7]
 [ 8  6  9]
 [12  8  9]]
Inverse matrix:
[[-0.08411215 -0.11682243  0.18224299]
 [ 0.1682243  -0.26635514  0.13551402]
 [-0.03738318  0.39252336 -0.25233645]]


Завдання 9: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від -8 до 8 та транспонуйте її.

In [10]:
matrix = np.random.uniform(-8, 8, size=(4, 4))
transposed_matrix = matrix.T

print(matrix)
print("Transposed matrix:")
print(transposed_matrix)

[[-0.94191468  0.10293895  5.82021878 -0.04629632]
 [ 0.57670094  4.63274859 -2.25293395 -1.91920103]
 [ 0.42352553  1.0406763  -6.95641504 -1.58543464]
 [ 0.36698006  4.86564344  6.37119102 -3.9301114 ]]
Transposed matrix:
[[-0.94191468  0.57670094  0.42352553  0.36698006]
 [ 0.10293895  4.63274859  1.0406763   4.86564344]
 [ 5.82021878 -2.25293395 -6.95641504  6.37119102]
 [-0.04629632 -1.91920103 -1.58543464 -3.9301114 ]]


Завдання 10: Створіть матрицю розміром 3x4 та вектор розміром 4 x1, заповніть їх випадковими
цілими числами в діапазоні від 1 до 10 та знайдіть середнє значення елементів матриці.

In [11]:
matrix = np.random.randint(1, 11, size=(3, 4))
vector = np.random.randint(1, 11, size=(4, 1))
average_value = np.mean(matrix)

print("Matrix:")
print(matrix)
print("Vector:")
print(vector)
print("Average value:")
print(average_value)

Matrix:
[[ 5  7  6  2]
 [ 8 10  9  3]
 [ 4  1  9  5]]
Vector:
[[6]
 [3]
 [3]
 [8]]
Average value:
5.75


Завдання 11: Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними
числами від 0 до 1, і знайдіть добуток матриці на вектор.


In [12]:
matrix = np.random.randint(1, 11, size=(2, 3))
vector = np.random.uniform(0, 1, size=(3, 1))
product = np.dot(matrix, vector)

print("Matrix:")
print(matrix)
print("Vector:")
print(vector)
print("Product:")
print(product)

Matrix:
[[ 2  3  9]
 [10  7  8]]
Vector:
[[0.11856155]
 [0.74359591]
 [0.6632106 ]]
Product:
[[ 8.43680629]
 [11.69647175]]


Завдання 12: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 10 та знайдіть їхню різницю.


In [13]:
matrix1 = np.random.randint(1, 11, size=(3, 3))
matrix2 = np.random.randint(1, 11, size=(3, 3))
difference = matrix1 - matrix2

print("Matrix1:")
print(matrix1)
print("Matrix2:")
print(matrix2)
print("Difference:")
print(difference)

Matrix1:
[[ 5  4  7]
 [10  2  7]
 [ 8  7  1]]
Matrix2:
[[ 7  6  6]
 [ 1  9 10]
 [ 7  3  3]]
Difference:
[[-2 -2  1]
 [ 9 -7 -3]
 [ 1  4 -2]]


Завдання 13: Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від -5 до 5 та знайдіть їх добуток.

In [14]:
matrix1 = np.random.randint(-5, 6, size=(3, 3))
matrix2 = np.random.randint(-5, 6, size=(3, 3))
product = np.dot(matrix1, matrix2)

print("Matrix1:")
print(matrix1)
print("Matrix2:")
print(matrix2)
print("Product:")
print(product)

Matrix1:
[[ 2  4  0]
 [ 3  5  4]
 [-3 -1 -1]]
Matrix2:
[[ 1 -5  0]
 [ 3  4  3]
 [ 1  1  4]]
Product:
[[14  6 12]
 [22  9 31]
 [-7 10 -7]]


Завдання 14: Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні
від -5 до 5 та знайдіть суму елементів матриці.

In [15]:
matrix = np.random.randint(-5, 6, size=(3, 3))
sum_of_elements = np.sum(matrix)

print(matrix)
print("Sum:")
print(sum_of_elements)

[[ 5 -4  1]
 [-2  3  3]
 [-5 -1  4]]
Sum:
4


Завдання 15: Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить добуток елементів
кожного рядка матриці.

In [16]:
matrix = np.random.uniform(0, 1, size=(4, 4))
row_products = np.prod(matrix, axis=1)
column_vector = row_products.reshape(-1, 1)

print(matrix)
print("Column vector:")
print(column_vector)

[[0.70383205 0.22315555 0.79679289 0.06424258]
 [0.63871895 0.9197492  0.4723665  0.58183168]
 [0.52839097 0.48517857 0.67673293 0.64552039]
 [0.38378485 0.41776998 0.21542674 0.04653209]]
Column vector:
[[0.0080398 ]
 [0.16145655]
 [0.1119913 ]
 [0.00160723]]


*Висновок*: Навчилась працювати з python та google colab